name: Test release

on:
  release:
    types: [published]

  workflow_dispatch:


jobs:
  test_linux_glibc223:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linux-version:
        - ubuntu:18.04
        - ubuntu:20.04
        - debian:buster
        - debian:bullseye
        - fedora:33
        - fedora:34
        - centos:stream8
        - amazonlinux:latest
        node-version: [ 14, 16 ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm run container release ${{ matrix.linux-version }} ${{ matrix.node-version }}
      env:
        MOCHA_TEST_NETWORK: 1


  test_linux_glibc228:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linux-version:
        - ubuntu:20.04
        - ubuntu:22.04
        - debian:bullseye
        - fedora:34
        - centos:stream8
        node-version: [ 18, 19 ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm run container release ${{ matrix.linux-version }} ${{ matrix.node-version }}
      env:
        MOCHA_TEST_NETWORK: 1


  test_winmac:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        platforms: [ windows-2019, macos-11 ]
        node-version: [ 14.x, 16.x, 18.x, 19.x ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npm install node-gyp
    - run: npx @mapbox/node-pre-gyp install
    - run: npx yatag
    - run: npm test
      env:
        MOCHA_TEST_NETWORK: 1
