# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bundled_gdal_coverage:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        node-version: [ 14.x ]
        platforms: [ ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp configure --debug
    - name: Build from sources
      run: npx @mapbox/node-pre-gyp build -j max --debug
    - name: Run unit tests
      run: npm test
    - run: npm run gcov
    - run: npm run codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  test_distros:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linux-version: [ 'ubuntu:16.04', 'ubuntu:18.04', 'centos:8', 'debian:buster', 'fedora:33', 'archlinux:latest' ]
        gdal-version: [ 'shared', 'bundled' ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm run container dev ${{ matrix.linux-version }} 14 ${{ matrix.gdal-version }}


  test_node:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10, 12, 14, 15, 16 ]
        gdal-version: [ 'shared', 'bundled' ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm run container dev ubuntu:20.04 ${{ matrix.node-version }} ${{ matrix.gdal-version }}
  

  test_winmac:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x, 16.x ]
        platforms: [ windows-2019, macos-10.15 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp configure
    - name: Build from sources
      run: npx @mapbox/node-pre-gyp build -j max
    - name: Run unit tests
      run: npm test
