# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      testNetwork:
        description: 'Run tests that require network connectivity'
        required: false
        default: 0

jobs:
  bundled_gdal_coverage:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        node-version: [ 14.x ]
        platforms: [ ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp configure --debug --enable_coverage
    - name: Build from sources
      run: npx @mapbox/node-pre-gyp build -j max --debug --enable_coverage
    - name: Run unit tests
      run: npm test
      env:
        MOCHA_TEST_NETWORK: 1
    - run: npm run gcov
    - run: npm run codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  test_distros:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linux-version: [ 'ubuntu:18.04', 'ubuntu:20.04', 'debian:buster', 'centos:8', 'fedora:33', 'archlinux:latest' ]
        gdal-version: [ 'shared', 'bundled' ]
        include:
          - linux-version: 'ubuntu:16.04'
            gdal-version: 'bundled'
          - linux-version: 'amazonlinux:latest'
            gdal-version: 'bundled'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm run container dev ${{ matrix.linux-version }} 14 ${{ matrix.gdal-version }}
      env:
        MOCHA_TEST_NETWORK: ${{ github.event.inputs.testNetwork }}


  test_node:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12, 14, 16 ]
        gdal-version: [ 'shared', 'bundled' ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm run container dev ubuntu:20.04 ${{ matrix.node-version }} ${{ matrix.gdal-version }}
      env:
        MOCHA_TEST_NETWORK: ${{ github.event.inputs.testNetwork }}


  test_winmac:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]
        platforms: [ windows-2019, macos-10.15 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp configure
    - name: Build from sources
      run: npx @mapbox/node-pre-gyp build -j max
    - name: Run unit tests
      run: npm test
      env:
        MOCHA_TEST_NETWORK: ${{ github.event.inputs.testNetwork }}
